NE-669: Add saga for cd add
NesloTechnologies/hennie-media-catalogue-react pull request #22
Opened 2024-10-08 11:09 UTC by HennieScheepersNeslo

2024-10-08 11:40 UTC, noydb requested changes

2024-10-08 11:40 UTC, noydb commented on src/cd/container/CDTable.container.jsx
> +    dispatch((deleteCD(id)));
why

2024-10-08 11:40 UTC, noydb commented on src/cd/container/CDAdd.container.jsx
> +import { addCDRequest } from '../../state/cd/cd.reducer';
what does addCDRequest do

2024-10-08 11:40 UTC, noydb commented on src/api/api.js
> +const httpPost = async (path, item) => {
I would suggest using this format, as we do in our other apps, so you can get used to it:
```js
const { endpoint, axiosOptions } = new ApiRequest(
      PROJECTS_ENDPOINT,
      HttpVerb.GET,
      getAuthHeaders()
    );

    const { data } = yield call(axios, endpoint, axiosOptions);

```

I would also suggest doing the above directly in the saga, I like the idea, but we don't need the api.js file. We can keep the saga functions small/simple enough to do all this logic directly in there

2024-10-08 11:40 UTC, noydb commented on src/api/api.js
> +const httpPost = async (path, item) => {
api request is in our ui-utils package

2024-10-08 11:40 UTC, noydb commented on src/jwt/jwt.js
> +let jwt = "";
what are we tryna do with this file

2024-10-08 11:40 UTC, noydb commented on src/state/cd/cd.reducer.js
> +    addCDRequest: (state) => {
I think it might be clearer to create a `setLoading` action, that just sets it to true or false.

then we should have just `addCD`, and `setLoading`. We should be able to remove add cd failure, and add cd request

2024-10-08 11:40 UTC, noydb commented on src/state/cd/cd.saga.js
> +    yield put(addCDSuccess(response.data))
missing semi colons. pls check all files

2024-10-08 11:40 UTC, noydb commented on src/state/cd/cd.saga.js
> +function* rootSaga() {
this should be more like:
```js
export default function* projectSaga() {
  yield all([
    watchForLoadAllProjects(),
    watchForCreateProjectRequest(),
    watchForSaveTeamMembersRequest(),
    watchForArchiveProject(),
    watchForReinstateProject()
  ]);
}
```

And then a watch function looks like this:
```js
export function* watchForReinstateProject() {
  yield takeLatest(REINSTATE_PROJECT, performReinstateProject);
}
```

2024-10-08 12:02 UTC, HennieScheepersNeslo commented on src/cd/container/CDAdd.container.jsx
> +import { addCDRequest } from '../../state/cd/cd.reducer';
This is the action being listened to by the sagas. It carries the CD to the saga to be further processed via action.payload

2024-10-09 06:51 UTC, noydb approved these changes

2024-10-09 06:52 UTC, merged