NE-676: aadd saga for dvd table
NesloTechnologies/hennie-media-catalogue-react pull request #29
Opened 2024-10-10 12:03 UTC by HennieScheepersNeslo

2024-10-10 12:23 UTC, noydb commented on src/state/dvd/dvd.reducer.js
> +    fetchDVDs: (state, action) => {
Should we maybe say fetchedDVDs? Since this is once the request is done. Sorry I'm still figuring out this redux flow

2024-10-10 12:35 UTC, HennieScheepersNeslo commented on src/state/dvd/dvd.reducer.js
> +    fetchDVDs: (state, action) => {
Yeah, this will be once the request is done. I think it would be more clear if I called it something like setDVDs or setDVDsState

2024-10-10 12:42 UTC, noydb commented on src/state/dvd/dvd.reducer.js
> +    fetchDVDs: (state, action) => {
Happy with that

2024-10-10 14:16 UTC, noydb requested changes

2024-10-10 14:16 UTC, noydb commented on src/dvd/container/DVDTable.container.jsx
> +    dispatch(setDVDsStateTrigger());
What does this do? This name is confusing

2024-10-10 14:16 UTC, noydb commented on src/state/cd/cd.reducer.js
> +    setCDsState: (state, action) => {
Let's try not say state in the name, state in react is useState. I know the store/reducer can be called state, but let's try not call it state to avoid confusion

2024-10-10 14:16 UTC, noydb commented on src/state/cd/cd.saga.js
> +    yield put(setCDsState(response.data));
This should just be setCDs

2024-10-10 14:16 UTC, noydb commented on src/state/cd/cd.saga.js
> -function* watchForLoadCDs() {
This was right

2024-10-10 14:16 UTC, noydb commented on src/state/dvd/dvd.reducer.js
> +    setDVDsStateTrigger: (state) => {
SetDVDsLoading?

2024-10-10 14:16 UTC, noydb commented on src/state/dvd/dvd.saga.js
> +function* setDVDsStateSaga() {
LoadDVDsSaga

2024-10-11 07:55 UTC, noydb requested changes
looking much better!!

2024-10-11 07:55 UTC, noydb commented on src/state/dvd/dvd.saga.js
> +function* watchForSetDVDs() {
watchForLoadDVDs

2024-10-11 08:22 UTC, noydb approved these changes

2024-10-11 08:22 UTC, merged